
# 容器配置，具体内容请联系运营人员获取
container:
  ip:
  code:
  token:
  auto: true

plugin:
  # 运行项目时的模式。分为开发环境(dev)、生产环境(prod)
  runMode: prod
  # 插件的路径。开发环境建议直接配置为插件模块的父级目录。例如: plugins。如果启动主程序时, 插件为加载, 请检查该配置是否正确。
  pluginPath: ./{{name}}-plugin
  # 插件配置文件
  pluginConfigFilePath: ./pluginFile

spring:
  datasource:
    dynamic:
      configClz: org.jangod.iweb.mapp.config.DataSourceConfig
      enabled: true
      primary: master
      strict: true
      datasource:
        master:
          driverClassName: org.h2.Driver
          url: jdbc:h2:mem:h2temp
        demo:
          driverClassName: com.mysql.jdbc.Driver
          url: 'jdbc:mysql://203.175.139.40:3306/dv_db_demo?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false'
          username: demo
          password: '123456a?'

app:
  l1ClassName: org.jangod.iweb.plugin.cache.redis.RedisCacheProvider
  redis:
    host: {{redisAddr}}
    port: {{redisPort}}
    database: {{redisDatabase}}
    password: '{{redisPassword}}'
    minIdle: 5
    maxTotal: 20
    maxIdle: 10
    maxWaitMillis: 10000


# mqtt配置
mqtt:
  broker: {{mqttAddr}}
  userName: {{mqttUsername}}
  passWord: {{mqttPassword}}
  qos: 2
  connectionTimeout: 10
  keepAliveInterval: 20
  clientId: {{mqttClientId}}
