container:
  auto: false
plugin:
  # 运行项目时的模式。分为开发环境(dev)、生产环境(prod)
  runMode: prod
  # 插件的路径。开发环境建议直接配置为插件模块的父级目录。例如: plugins。如果启动主程序时, 插件为加载, 请检查该配置是否正确。
  pluginPath: ./gztask-plugin
  # 插件配置文件
  pluginConfigFilePath: ./pluginFile

spring:
  cloud:
    sentinel:
      enabled: false
  datasource:
    dynamic:
      configClz: org.jangod.iweb.mapp.config.DataSourceConfig
      enabled: true
      primary: master
      strict: true
      datasource:
        master:
          driverClassName: org.h2.Driver
          url: jdbc:h2:mem:h2temp

app:
  simple:
    enabled: true
  # 关闭nacos
  nacos:
    enabled: false
  # dubbo
  dubbo:
    enabled: ${args.dubbo.enabled:true}
  # 服务发现
  discovery:
    # 通过redis的策略找服务（值为redis，app.nacos.enabled必须配置为false）
    type: redis
    fixed:
      csp-uaa: "127.0.0.1:${server.port}"
  # 单点登陆配置
  sso:
    uaa:
      enabled: false    #禁止sso单点转发（主要开发环境使用）
    none:
      enabled: true
      appCode: 'gztask'
      companyIdVal: 'inspur'
      companyNameVal: ''
      dashboardFlag: '1'
      defaultFlag: '1'
      epdomain: '127.0.0.1'
      mainTitle: '广州市一体化平台'
      mainLogo: 'logo.png'
      loginThemeId: 'cool'
      parentDeptCode: '广州市'

  # redis配置
  l1ClassName: org.jangod.iweb.plugin.cache.redis.RedisCacheProvider
  redis:
    host: ${args.redis.host}
    port: ${args.redis.port:6379}
    database: ${args.redis.database:9}
    password: ${args.redis.password}
    minIdle: 5
    maxTotal: 20
    maxIdle: 10
    maxWaitMillis: 10000

  # dubbo服务配置
dubbo:
  protocol:
    port: 20880
  registry:
    address: ${args.dubbo.address}
    protocol: zookeeper
  application:
    name: gztask
    group: ${args.dubbo.group}
